export const initialTasks = [
  {
    id: 1,
    title: "Buy groceries",
    description: "Buy milk, bread, eggs, and fruits from the supermarket.",
    dueDate: "2024-05-25",
    priority: "High",
    category: "Personal",
    notes: "Check for discounts on dairy products.",
    reminder: true,
    completed: false,
  },
  {
    id: 2,
    title: "Complete project report",
    description: "Finish the project report for the Q2 review meeting.",
    dueDate: "2024-05-30",
    priority: "Medium",
    category: "Work",
    notes:
      "Include the latest sales data and feedback from the marketing team.",
    reminder: true,
    completed: false,
  },
  {
    id: 3,
    title: "Workout",
    description: "Morning workout session at the gym.",
    dueDate: "2024-05-20",
    priority: "Low",
    category: "Fitness",
    notes: "Focus on leg exercises.",
    reminder: false,
    completed: true,
  },
  {
    id: 4,
    title: "Plan vacation",
    description: "Plan the summer vacation trip.",
    dueDate: "2024-06-15",
    priority: "Medium",
    category: "Personal",
    notes: "Look for travel packages and discounts.",
    reminder: true,
    completed: false,
  },
  {
    id: 5,
    title: "Team meeting",
    description: "Weekly sync-up with the development team.",
    dueDate: "2024-05-21",
    priority: "High",
    category: "Work",
    notes: "Discuss project milestones and blockers.",
    reminder: true,
    completed: false,
  },
  {
    id: 6,
    title: "React Study",
    description: "Weekly sync-up with the development team.",
    dueDate: "2024-06-21",
    priority: "High",
    category: "Study",
    notes: "Discuss project milestones and blockers.",
    reminder: true,
    completed: false,
  },
  {
    id: 7,
    title: "Go to the GYM",
    description: "Weekly sync-up with the development team.",
    dueDate: "2024-06-28",
    priority: "High",
    category: "Fitness",
    notes: "Discuss project milestones and blockers.",
    reminder: true,
    completed: false,
  },
];